'use client';

import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Loader2, Send } from 'lucide-react';
import type { SummarizePdfOutput } from '@/ai/flows/summarize-pdf';
import type { ChatWithPdfOutput } from '@/ai/flows/chat-with-pdf';
import type { GenerateGlossaryOutput } from '@/ai/flows/glossary-flow';
import type { ExplainTextOutput } from '@/ai/flows/explain-text-flow';
import type { GenerateQuizOutput } from '@/ai/schemas/quiz';
import type { QuizQuestion } from '@/ai/schemas/quiz';
import { ScrollArea } from './ui/scroll-area';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { RadioGroup, RadioGroupItem } from './ui/radio-group';
import { Label } from './ui/label';
import { cn } from '@/lib/utils';

export type AiDialogType = 'summary' | 'key-points' | 'chat' | 'glossary' | 'explain' | 'quiz';

type AiDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  type: AiDialogType;
  isLoading: boolean;
  summaryOutput: SummarizePdfOutput | null;
  chatOutput: ChatWithPdfOutput | null;
  glossaryOutput: GenerateGlossaryOutput | null;
  explanationOutput: ExplainTextOutput | null;
  quizOutput: GenerateQuizOutput | null;
  onChatSubmit: (question: string) => void;
};

const AiDialog: React.FC<AiDialogProps> = ({
  open,
  onOpenChange,
  type,
  isLoading,
  summaryOutput,
  chatOutput,
  glossaryOutput,
  explanationOutput,
  quizOutput,
  onChatSubmit,
}) => {
  const [question, setQuestion] = useState('');

  const handleChatSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (question.trim()) {
      onChatSubmit(question);
      setQuestion('');
    }
  };

  const renderLoading = (text: string) => (
    <div className="flex items-center justify-center space-x-2 h-full p-8">
      <Loader2 className="animate-spin" />
      <span>{text}</span>
    </div>
  )

  const renderSummaryContent = () => (
    <>
      <DialogHeader>
        <DialogTitle>AI Analysis</DialogTitle>
        <DialogDescription>
          Here's a summary and key points generated by the AI based on the document's content.
        </DialogDescription>
      </DialogHeader>
      <Tabs defaultValue={type === 'key-points' ? 'key-points' : 'summary'} className="w-full pt-4">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="summary">Summary</TabsTrigger>
          <TabsTrigger value="key-points">Key Points</TabsTrigger>
        </TabsList>
        <ScrollArea className="h-96">
          <TabsContent value="summary" className="p-4">
            <h3 className="text-lg font-semibold mb-2">Summary</h3>
            {isLoading ? renderLoading('Generating summary...') : (
              <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                {summaryOutput?.summary || 'No summary available.'}
              </p>
            )}
          </TabsContent>
          <TabsContent value="key-points" className="p-4">
            <h3 className="text-lg font-semibold mb-2">Key Points</h3>
            {isLoading ? renderLoading('Extracting key points...') : (
              <ul className="list-disc pl-5 space-y-2 text-sm text-muted-foreground">
                {summaryOutput?.keyPoints?.map((point, index) => (
                  <li key={index}>{point}</li>
                )) || <li>No key points available.</li>}
              </ul>
            )}
          </TabsContent>
        </ScrollArea>
      </Tabs>
    </>
  );

  const renderGlossaryContent = () => (
    <>
        <DialogHeader>
            <DialogTitle>Glossary</DialogTitle>
            <DialogDescription>Key terms and concepts identified from the document by the AI.</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-96 pr-4">
            {isLoading ? renderLoading('Creating glossary...') : (
                 <Accordion type="single" collapsible className="w-full">
                    {glossaryOutput?.glossary?.map((item, index) => (
                        <AccordionItem value={`item-${index}`} key={index}>
                            <AccordionTrigger>{item.term}</AccordionTrigger>
                            <AccordionContent>
                                {item.definition}
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            )}
        </ScrollArea>
    </>
  );
  
  const renderExplanationContent = () => (
    <>
        <DialogHeader>
            <DialogTitle>Explanation</DialogTitle>
            <DialogDescription>Here is a simplified explanation of the selected text.</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-auto max-h-96 pr-4 mt-4">
            {isLoading ? renderLoading('Thinking...') : (
                <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                    {explanationOutput?.explanation || 'No explanation available.'}
                </p>
            )}
        </ScrollArea>
    </>
  );

  const QuizView: React.FC<{ questions: QuizQuestion[] }> = ({ questions }) => {
    const [answers, setAnswers] = useState<Record<number, string>>({});
    const [submitted, setSubmitted] = useState(false);
  
    const handleAnswerChange = (questionIndex: number, value: string) => {
      setAnswers(prev => ({ ...prev, [questionIndex]: value }));
    };
  
    const handleSubmit = () => {
      setSubmitted(true);
    };

    const getResultColor = (index: number, option?: string) => {
        if (!submitted) return '';
        const question = questions[index];
        const isCorrect = question.answer === answers[index];
        
        if(option) { // For multiple choice options
            if(option === question.answer) return 'text-green-700 font-bold';
            if(option === answers[index] && !isCorrect) return 'text-red-700';
        } else { // For the explanation text
            return isCorrect ? 'text-green-700' : 'text-red-700';
        }
        return '';
    }
  
    return (
      <div className="space-y-6">
        {questions.map((q, index) => (
          <Card key={index}>
            <CardHeader>
              <CardTitle>Question {index + 1}</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>{q.question}</p>
              {q.type === 'multiple-choice' && (
                <RadioGroup 
                    onValueChange={(value) => handleAnswerChange(index, value)}
                    disabled={submitted}
                    value={answers[index]}
                >
                  {q.options?.map((option, i) => (
                    <div key={i} className="flex items-center space-x-2">
                      <RadioGroupItem value={option} id={`q${index}-o${i}`} />
                      <Label htmlFor={`q${index}-o${i}`} className={cn(getResultColor(index, option))}>
                        {option}
                      </Label>
                    </div>
                  ))}
                </RadioGroup>
              )}
              {q.type === 'true-false' && (
                 <RadioGroup 
                    onValueChange={(value) => handleAnswerChange(index, value)}
                    disabled={submitted}
                    value={answers[index]}
                >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="True" id={`q${index}-true`} />
                      <Label htmlFor={`q${index}-true`} className={cn(getResultColor(index, "True"))}>True</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="False" id={`q${index}-false`} />
                      <Label htmlFor={`q${index}-false`} className={cn(getResultColor(index, "False"))}>False</Label>
                    </div>
                </RadioGroup>
              )}
              {submitted && (
                 <div className={cn("p-4 rounded-md text-sm bg-muted", getResultColor(index))}>
                    <p className="font-bold">Correct Answer: {q.answer}</p>
                    <p>{q.explanation}</p>
                 </div>
              )}
            </CardContent>
          </Card>
        ))}
        {!submitted && (
            <Button onClick={handleSubmit} className="w-full">Submit Answers</Button>
        )}
      </div>
    );
  };
  
  const renderQuizContent = () => (
    <>
        <DialogHeader>
            <DialogTitle>AI-Generated Quiz</DialogTitle>
            <DialogDescription>Test your knowledge with these questions based on the document.</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[32rem] pr-4 mt-4">
            {isLoading ? renderLoading('Generating your quiz...') : (
                quizOutput?.quiz && <QuizView questions={quizOutput.quiz} />
            )}
        </ScrollArea>
    </>
  );

  const renderChatContent = () => (
    <div className="flex flex-col h-[32rem]">
      <DialogHeader>
        <DialogTitle>Ask a Question</DialogTitle>
        <DialogDescription>
          Ask a question about the document, and the AI will find the answer for you.
        </DialogDescription>
      </DialogHeader>
      <ScrollArea className="flex-1 my-4">
         <div className="p-4 space-y-4">
            {isLoading && !chatOutput ? renderLoading('Thinking...') : (
                chatOutput && (
                    <div className="p-3 rounded-md bg-muted">
                        <p className="text-sm">{chatOutput.answer}</p>
                    </div>
                )
            )}
             {isLoading && chatOutput && (
                <div className="flex items-center space-x-2">
                    <Loader2 className="animate-spin h-4 w-4" />
                    <span>Thinking...</span>
                </div>
             )}
        </div>
      </ScrollArea>
      <DialogFooter>
        <form onSubmit={handleChatSubmit} className="flex w-full space-x-2">
          <Input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Type your question here..."
            disabled={isLoading}
          />
          <Button type="submit" disabled={isLoading || !question.trim()}>
            {isLoading ? <Loader2 className="animate-spin" /> : <Send />}
          </Button>
        </form>
      </DialogFooter>
    </div>
  );

  const renderContent = () => {
    switch (type) {
        case 'summary':
        case 'key-points':
            return renderSummaryContent();
        case 'glossary':
            return renderGlossaryContent();
        case 'explain':
            return renderExplanationContent();
        case 'quiz':
            return renderQuizContent();
        case 'chat':
            return renderChatContent();
        default:
            return null;
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        {renderContent()}
      </DialogContent>
    </Dialog>
  );
};

export default AiDialog;
